version: "3.7"

services:

    database:
        image: mongo:latest
        ports:
            - 27017:27017
        container_name: database
        volumes: 
            - ~/docker/mongodb-data:/data/db
    
    frontend:
        image: devops-app-frontend:latest
        ports:
            - 4200:80
        container_name: frontend

    backend:
        image: devops-app-backend:latest
        ports:
            - 3000:3000
        container_name: backend
        depends_on:
            - database
        