apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: felipegleon/devops-app-backend:v1
        ports:
        - containerPort: 3000
        env: 
        # - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: database-secret
        #       key: mongo-root-username
        # - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        #   valueFrom: 
        #     secretKeyRef:
        #       name: database-secret
        #       key: mongo-root-password
        - name: DATABASE_SERVER
          valueFrom: 
            configMapKeyRef:
              name: database-configmap
              key: database_url
      imagePullSecrets:
        - name: regcred 
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000